name: Ubuntu
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
      
      
